import { docMarkdown, escapeText, markdownTable, nodeId } from './markdown';

describe('markdown helpers', () => {
  it('escapes characters Mermaid reads as syntax', () => {
    expect(escapeText('GET /invoices/{id}')).toBe('GET /invoices/#123;id#125;');
    expect(escapeText('a || b; "c" <d> #e')).toBe('a #124;#124; b#59; #34;c#34; #60;d#62; #35;e');
  });

  it('makes node ids from any text', () => {
    expect(nodeId('volume', 'postgres-data')).toBe('volume_postgres_data');
  });

  it('escapes pipes inside table cells', () => {
    expect(markdownTable(['A'], [['x | y']])).toBe('| A |\n| --- |\n| x \\| y |');
  });

  it('puts the generated notice, title, intro and sections in order', () => {
    const markdown = docMarkdown({
      file: 'x.md',
      title: 'Title',
      intro: 'Intro.',
      sections: [{ heading: 'One', body: 'Body.' }],
    });
    expect(markdown.split('\n\n')).toEqual([
      '<!-- Generated by `npm run diagrams`. Edit the code it is read from, not this file. -->',
      '# Title',
      'Intro.',
      '## One',
      'Body.',
    ]);
  });
});
