import path from 'node:path';

export const REPO_ROOT = path.resolve(__dirname, '../../..');
export const DIAGRAMS_DIR = path.join(REPO_ROOT, 'docs', 'diagrams');

export interface Section {
  heading: string;
  body: string;
}

export interface Doc {
  file: string;
  title: string;
  intro: string;
  sections: Section[];
}

export function docMarkdown(doc: Doc): string {
  return [
    '<!-- Generated by `npm run diagrams`. Edit the code it is read from, not this file. -->',
    `# ${doc.title}`,
    doc.intro,
    ...doc.sections.map(({ heading, body }) => `## ${heading}\n\n${body}`),
  ].join('\n\n');
}

export function mermaid(lines: string[]): string {
  return ['```mermaid', ...lines, '```'].join('\n');
}

export function markdownTable(head: string[], rows: string[][]): string {
  const row = (cells: string[]) =>
    `| ${cells.map((cell) => cell.replace(/\|/g, '\\|')).join(' | ')} |`;
  return [row(head), row(head.map(() => '---')), ...rows.map(row)].join('\n');
}

export const code = (value: string): string => `\`${value}\``;

// Mermaid reads these characters as syntax inside labels and messages. Its #<code>; entities
// are turned back into the character when the diagram is drawn.
export function escapeText(value: string): string {
  return value.replace(/["#;<>`|{}]/g, (char) => `#${char.charCodeAt(0)};`);
}

// Node ids: letters, digits and underscores only.
export function nodeId(...parts: string[]): string {
  return parts.join('_').replace(/[^A-Za-z0-9_]/g, '_');
}

// Locale-independent, so output is identical on every machine.
export function byText(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}
